import { Poppins } from 'next/font/google'
import type { Metadata } from 'next'

import './globals.css'
import Header from './components/header'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
const poppins = Poppins({
  variable: "--font-poppins-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  )
}
