import { Poppins } from 'next/font/google'
import type { Metadata } from 'next'

import './globals.css'
import { Header } from './components/header'
import { Navbar } from './components/navbar'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
const poppins = Poppins({
  subsets: ["latin"],
  weight: ['100', "400", "500", "700"],
});
 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Header />
        <Navbar />
        {children}
      </body>
    </html>
  )
}
