import { Poppins } from 'next/font/google'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  display: 'swap',
})
 

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={poppins.className}>
      <body>{children}</body>
    </html>
  )
}
