import joystick from "@/public/joystick.png";
import fone from "@/public/fone.png";
import laptop from "@/public/laptop.png";
import joystickYellow from "@/public/joystick-product.png";


export const mock = [
  {
    id: 1,
    name: "Play Game",
    price: 11.9,
    image: joystick,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 2,
    name: "laptop",
    price: 23.9,
    image: laptop,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 3,
    name: "Fone",
    price: 11.9,
    image: fone,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 4,
    name: "Play Game",
    price: 11.9,
    image: joystick,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 5,
    name: "Joystick",
    price: 11.9,
    image: joystickYellow,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 6,
    name: "Fone",
    price: 11.9,
    image: fone,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 7,
    name: "laptop",
    price: 2399.9,
    image: laptop,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 8,
    name: "Joystick",
    price: 11.9,
    image: joystickYellow,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
  {
    id: 9,
    name: "Joystick",
    price: 11.9,
    image: joystickYellow,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
    colors: ["#FBBF24", "#FBBF24"],
    sizes: [30, 42, 48, 56],
    quantity: 55,
    stars: 0,
  },
];

export const mockLike = [1,2,4,7]

export const mockCart = [
  {
    id: 1,
    name: "Play Game",
    color: "green",
    size: 38,
    quantity: 3,
    price: 11.9,
    image:joystick,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
  },{
    id: 7,
    color:"blue",
    size: 42,
    quantity: 1,
    name: "laptop",
    price: 2399.9,
    image: joystickYellow,
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    sku: "01133-9-9",
    categories: ["20% off", "49% off Alex remote"],
    availability: "In Stock",
    reviews: 0,
  },
];
